version: '3'
services:
    learn_ml:
        container_name: learn_ml
        # image: pytorch/pytorch:1.9.0-cuda10.2-cudnn7-devel
        restart: always
        entrypoint: /bin/bash
        # entrypoint: >
        #     jupyter-lab
        #     --allow-root
        #     --ip=0.0.0.0
        #     --port=8888
        #     --no-browser
        #     --NotebookApp.token=''
        #     --notebook-dir=/home/user/notebooks
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./notebooks:/home/user/notebooks
            - ./input:/home/user/input
            - ./models:/home/user/models
            - ./src:/home/user/src
        environment:
            - JUPYTER_ENABLE_LAB=true
        runtime: nvidia
        tty: true
        ports:
            - 8889:8889